/**
 * Nexor WhatsApp Extractor — Bookmarklet source
 *
 * This code runs directly in web.whatsapp.com when the user clicks the bookmarklet.
 * It injects a floating UI with extraction buttons.
 *
 * IMPORTANT: every statement MUST end with ; for safe minification.
 * Uses DOM scraping with stable ARIA roles (same technique as 58k-user extensions).
 */

export const BOOKMARKLET_CODE = `(function(){
if(window.__nexorLoaded){var e=document.getElementById('nexor-ui');if(e){e.style.display='block';return;}window.__nexorLoaded=false;}
window.__nexorLoaded=true;
var sleep=function(ms){return new Promise(function(r){setTimeout(r,ms);});};
var getPane=function(){return document.querySelector('#pane-side [role="grid"]')||document.querySelector('[aria-label="Lista de chats"]')||document.querySelector('[aria-label="Chat list"]')||document.querySelector('#pane-side');};
var getItems=function(){var p=getPane();if(!p)return[];return Array.from(p.querySelectorAll('[role="listitem"],[role="row"]')).filter(function(el){return el.querySelector('span[title]');});};
var getDialog=function(){return document.querySelector('[role="dialog"]');};
var rClick=function(el){if(!el)return false;try{var r=el.getBoundingClientRect();var o={bubbles:true,cancelable:true,view:window,clientX:r.left+r.width/2,clientY:r.top+r.height/2};el.dispatchEvent(new MouseEvent('mousedown',o));el.dispatchEvent(new MouseEvent('mouseup',o));el.dispatchEvent(new MouseEvent('click',o));return true;}catch(e){return false;}};
var cleanPhone=function(s){if(!s)return null;var d=String(s).replace(/\\D/g,'');if(d.length<8||d.length>15)return null;return '+'+d;};
var waitFor=async function(fn,to){to=to||8000;var st=Date.now();while(Date.now()-st<to){var r=fn();if(r)return r;await sleep(200);}return null;};
var closeDialog=async function(){var d=getDialog();if(!d)return;var b=d.querySelector('[aria-label="Cerrar"],[aria-label="Close"],button[aria-label*="errar"]');if(b){rClick(b);await sleep(300);}else{document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',keyCode:27,bubbles:true}));await sleep(300);}};
var scrollAll=async function(c,max){max=max||40;if(!c)return;var lh=-1,st=0;for(var i=0;i<max;i++){c.scrollTop=c.scrollHeight;await sleep(350);if(c.scrollHeight===lh){st++;if(st>=3)break;}else st=0;lh=c.scrollHeight;}c.scrollTop=0;await sleep(400);};
var extractRow=function(row){if(!row)return null;var phone=null,name=null;var img=row.querySelector('img');if(img&&img.src){var m=img.src.match(/[?&]u=(\\d{8,15})/);if(m)phone='+'+m[1];}if(!phone){var ss=row.querySelectorAll('span[title]');for(var i=0;i<ss.length;i++){var t=ss[i].getAttribute('title')||'';if(/^\\s*\\+?\\d[\\d\\s\\-\\(\\)]{7,20}\\d\\s*$/.test(t)){phone=cleanPhone(t);if(phone)break;}}}if(!phone){var txt=row.innerText||'';var mm=txt.match(/\\+\\d[\\d\\s\\-\\(\\)]{7,20}\\d/);if(mm)phone=cleanPhone(mm[0]);}var spans=row.querySelectorAll('span[title]');for(var j=0;j<spans.length;j++){var tt=(spans[j].getAttribute('title')||'').trim();if(!tt)continue;if(/^\\+?\\d[\\d\\s\\-\\(\\)]+$/.test(tt))continue;if(/^(you|tú|tu)$/i.test(tt))continue;name=tt;break;}return phone?{phone:phone,name:name||''}:null;};
var log=function(msg,type){var l=document.getElementById('nexor-log');if(!l)return;var e=document.createElement('div');e.style.cssText='margin-bottom:3px;'+(type==='error'?'color:#ef4444':type==='success'?'color:#22c55e':'color:rgba(255,255,255,0.7)');e.textContent='> '+msg;l.appendChild(e);l.scrollTop=l.scrollHeight;};
var clearLog=function(){var l=document.getElementById('nexor-log');if(l)l.innerHTML='';};
var downloadCsv=function(rows,filename,mode){if(!rows||rows.length===0){log('Sin contactos','error');return;}var includeName=mode==='phone_name';var headers=includeName?['Teléfono','Nombre']:['Teléfono'];var lines=[headers.join(',')];for(var i=0;i<rows.length;i++){var r=rows[i];var c=['"'+(r.phone||'').replace(/"/g,'""')+'"'];if(includeName)c.push('"'+(r.name||'').replace(/"/g,'""')+'"');lines.push(c.join(','));}var blob=new Blob(['\\ufeff'+lines.join('\\n')],{type:'text/csv;charset=utf-8'});var url=URL.createObjectURL(blob);var a=document.createElement('a');a.href=url;a.download=filename+'_'+Date.now()+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);log('Descarga iniciada','success');};
var extractGroup=async function(item,groupName){var contacts=[];var seen=new Set();try{rClick(item);await sleep(800);var header=document.querySelector('#main header');if(!header)throw new Error('header no encontrado');var hc=header.querySelector('[role="button"]')||header.firstElementChild;if(!hc)throw new Error('header click');rClick(hc);await sleep(1500);var dialog=await waitFor(getDialog,5000);if(!dialog)throw new Error('panel no se abrió');var scrollable=null;var all=dialog.querySelectorAll('div');for(var i=0;i<all.length;i++){var el=all[i];var ss=getComputedStyle(el);if((ss.overflowY==='auto'||ss.overflowY==='scroll')&&el.scrollHeight>el.clientHeight){scrollable=el;break;}}var viewAll=Array.from(dialog.querySelectorAll('[role="button"]')).find(function(b){var t=(b.textContent||'').toLowerCase();return /ver\\s+todos|view\\s+all/.test(t);});if(viewAll){rClick(viewAll);await sleep(800);}var noNew=0,sTop=0;for(var it=0;it<150;it++){var rows=Array.from(dialog.querySelectorAll('[role="listitem"]'));var added=0;for(var ri=0;ri<rows.length;ri++){var c=extractRow(rows[ri]);if(!c)continue;if(seen.has(c.phone))continue;seen.add(c.phone);contacts.push({phone:c.phone,name:c.name,source:'Grupo: '+groupName});added++;}if(added===0){noNew++;if(noNew>=4)break;}else noNew=0;if(scrollable){sTop+=500;scrollable.scrollTop=sTop;}await sleep(350);}}catch(e){log('Error: '+e.message,'error');}await closeDialog();return contacts;};
var extractAllGroups=async function(mode){clearLog();log('Cargando lista de chats...');var pane=getPane();if(!pane){log('Abrí WhatsApp Web primero','error');return;}await scrollAll(pane);var items=getItems();var groups=[];for(var i=0;i<items.length;i++){var isG=!!items[i].querySelector('[data-icon*="default-group"]');if(!isG)continue;var n=items[i].querySelector('span[title]');var gname=n?n.getAttribute('title')||'Sin nombre':'Sin nombre';groups.push({index:i,name:gname});}log(groups.length+' grupos encontrados','success');if(groups.length===0)return;var allContacts=[];var seen=new Set();for(var gi=0;gi<groups.length;gi++){log('Grupo '+(gi+1)+'/'+groups.length+': '+groups[gi].name);var fresh=getItems();var freshItem=fresh[groups[gi].index];if(!freshItem){log('  saltado','error');continue;}var contacts=await extractGroup(freshItem,groups[gi].name);log('  '+contacts.length+' contactos','success');for(var ci=0;ci<contacts.length;ci++){if(seen.has(contacts[ci].phone))continue;seen.add(contacts[ci].phone);allContacts.push(contacts[ci]);}}log('Total: '+allContacts.length+' contactos únicos','success');downloadCsv(allContacts,'nexor_grupos',mode);};
var extractLabels=async function(mode){clearLog();var sys=['todos','all','no leídos','unread','no leidos','favoritos','favorites','grupos','groups','comunidades','communities'];var tabs=Array.from(document.querySelectorAll('[role="tab"],[aria-selected]'));var labels=[];var seenN=new Set();for(var i=0;i<tabs.length;i++){var n=(tabs[i].textContent||'').trim();if(!n||n.length>50)continue;if(sys.indexOf(n.toLowerCase())>=0)continue;if(/^\\d+$/.test(n))continue;if(seenN.has(n))continue;seenN.add(n);labels.push({name:n,tab:tabs[i]});}if(labels.length===0){log('Sin etiquetas (requiere WhatsApp Business)','error');return;}log(labels.length+' etiquetas','success');var all=[];var seen=new Set();for(var li=0;li<labels.length;li++){var label=labels[li];log('Etiqueta: '+label.name);rClick(label.tab);await sleep(900);var pane=getPane();if(!pane)continue;await scrollAll(pane,20);var items=getItems();for(var ii=0;ii<items.length;ii++){var fresh=getItems();var it=fresh[ii];if(!it)continue;var nn=it.querySelector('span[title]');var name=nn?nn.getAttribute('title')||'':'';rClick(it);await sleep(500);var header=document.querySelector('#main header');if(!header)continue;var hc=header.querySelector('[role="button"]')||header.firstElementChild;if(!hc)continue;rClick(hc);await sleep(700);var dialog=getDialog();if(dialog){var txt=dialog.innerText||'';var m=txt.match(/\\+\\d[\\d\\s\\-\\(\\)]{7,20}\\d/);if(m){var phone=cleanPhone(m[0]);if(phone&&!seen.has(phone)){seen.add(phone);all.push({phone:phone,name:name,source:'Etiqueta: '+label.name});}}await closeDialog();}}}log('Total: '+all.length,'success');downloadCsv(all,'nexor_etiquetas',mode);};
var extractAllChats=async function(mode){clearLog();var pane=getPane();if(!pane){log('Abrí WhatsApp Web','error');return;}log('Cargando...');await scrollAll(pane);var items=getItems();var nonG=[];for(var i=0;i<items.length;i++){if(items[i].querySelector('[data-icon*="default-group"]'))continue;var n=items[i].querySelector('span[title]');nonG.push({index:i,name:n?n.getAttribute('title')||'':''});}log(nonG.length+' chats');var all=[];var seen=new Set();for(var ii=0;ii<nonG.length;ii++){var fresh=getItems();var it=fresh[nonG[ii].index];if(!it)continue;rClick(it);await sleep(450);var header=document.querySelector('#main header');if(!header)continue;var hc=header.querySelector('[role="button"]')||header.firstElementChild;if(!hc)continue;rClick(hc);await sleep(650);var dialog=getDialog();if(dialog){var txt=dialog.innerText||'';var m=txt.match(/\\+\\d[\\d\\s\\-\\(\\)]{7,20}\\d/);if(m){var phone=cleanPhone(m[0]);if(phone&&!seen.has(phone)){seen.add(phone);all.push({phone:phone,name:nonG[ii].name,source:'Chat'});}}await closeDialog();}if(ii%10===0)log('  '+ii+'/'+nonG.length);}log('Total: '+all.length,'success');downloadCsv(all,'nexor_chats',mode);};
var ui=document.createElement('div');
ui.id='nexor-ui';
ui.innerHTML='<div id="nx-head" style="padding:14px 16px;background:linear-gradient(135deg,#B45309,#D97706,#FFD700);color:#000;font-weight:900;font-size:13px;display:flex;align-items:center;justify-content:space-between;cursor:move;border-radius:12px 12px 0 0"><span>🔥 NEXOR EXTRACTOR</span><span id="nx-close" style="cursor:pointer;font-size:18px;padding:0 6px">×</span></div><div style="padding:14px"><div style="font-size:10px;font-weight:700;color:rgba(255,255,255,0.4);text-transform:uppercase;margin-bottom:8px">Modo</div><div style="display:flex;gap:6px;margin-bottom:14px"><button id="nx-m1" style="flex:1;padding:8px;background:rgba(217,119,6,0.15);border:1px solid rgba(217,119,6,0.5);border-radius:8px;color:#FFD700;font-size:10px;font-weight:700;cursor:pointer">Solo teléfono</button><button id="nx-m2" style="flex:1;padding:8px;background:transparent;border:1px solid rgba(255,255,255,0.1);border-radius:8px;color:rgba(255,255,255,0.5);font-size:10px;font-weight:700;cursor:pointer">Teléfono + Nombre</button></div><div style="font-size:10px;font-weight:700;color:rgba(255,255,255,0.4);text-transform:uppercase;margin-bottom:8px">Extraer</div><button id="nx-g" style="width:100%;padding:12px;margin-bottom:6px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:10px;color:#fff;font-size:12px;font-weight:700;cursor:pointer;text-align:left">👥 Todos los grupos</button><button id="nx-l" style="width:100%;padding:12px;margin-bottom:6px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:10px;color:#fff;font-size:12px;font-weight:700;cursor:pointer;text-align:left">🏷️ Todas las etiquetas</button><button id="nx-a" style="width:100%;padding:12px;margin-bottom:12px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:10px;color:#fff;font-size:12px;font-weight:700;cursor:pointer;text-align:left">💬 Todos los chats</button><div id="nexor-log" style="max-height:180px;overflow-y:auto;padding:10px;background:rgba(0,0,0,0.4);border:1px solid rgba(255,255,255,0.05);border-radius:8px;font-family:monospace;font-size:10px;line-height:1.5;color:rgba(255,255,255,0.7)"></div></div>';
ui.style.cssText='position:fixed;top:20px;right:20px;width:300px;background:#06060A;border:1px solid rgba(255,255,255,0.1);border-radius:12px;box-shadow:0 10px 40px rgba(0,0,0,0.5);z-index:2147483647;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif;color:#fff';
document.body.appendChild(ui);
var mode='phone';
document.getElementById('nx-m1').onclick=function(){mode='phone';this.style.cssText='flex:1;padding:8px;background:rgba(217,119,6,0.15);border:1px solid rgba(217,119,6,0.5);border-radius:8px;color:#FFD700;font-size:10px;font-weight:700;cursor:pointer';document.getElementById('nx-m2').style.cssText='flex:1;padding:8px;background:transparent;border:1px solid rgba(255,255,255,0.1);border-radius:8px;color:rgba(255,255,255,0.5);font-size:10px;font-weight:700;cursor:pointer';};
document.getElementById('nx-m2').onclick=function(){mode='phone_name';this.style.cssText='flex:1;padding:8px;background:rgba(217,119,6,0.15);border:1px solid rgba(217,119,6,0.5);border-radius:8px;color:#FFD700;font-size:10px;font-weight:700;cursor:pointer';document.getElementById('nx-m1').style.cssText='flex:1;padding:8px;background:transparent;border:1px solid rgba(255,255,255,0.1);border-radius:8px;color:rgba(255,255,255,0.5);font-size:10px;font-weight:700;cursor:pointer';};
document.getElementById('nx-g').onclick=function(){extractAllGroups(mode);};
document.getElementById('nx-l').onclick=function(){extractLabels(mode);};
document.getElementById('nx-a').onclick=function(){extractAllChats(mode);};
document.getElementById('nx-close').onclick=function(){ui.remove();window.__nexorLoaded=false;};
var drag=false,oX=0,oY=0;
var h=document.getElementById('nx-head');
h.onmousedown=function(e){drag=true;oX=e.clientX-ui.offsetLeft;oY=e.clientY-ui.offsetTop;};
document.addEventListener('mousemove',function(e){if(drag){ui.style.left=(e.clientX-oX)+'px';ui.style.right='auto';ui.style.top=(e.clientY-oY)+'px';}});
document.addEventListener('mouseup',function(){drag=false;});
log('Nexor Extractor v3.1 listo','success');
})();`
